service:
  name: velogthumb

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-apigw-binary
  
custom:
  webpack:
    includeModules: true
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2

functions:
  resize:
    handler: src/handler.resize
    events:
      - http:
          method: get
          path: resize
